### ISSUE TITLE
How to Cite?

### ISSUE THREAD

**Issue by fpedd** [PacktPublishing/TinyML-Cookbook#1]
Could you please provide a BibTeX entry? Maybe smth. along the lines of this in your `Readme.md`
```
@book{iodice2020tinyml,
  title={TinyML Cookbook: Combine artificial intelligence and ultra-low-power embedded devices to make the world smarter},
  author={Gian Marco Iodice},
  year={2022},
  publisher={Packt Publishing}
}
```
or add a `CITATION.cff`?

Thank you for the great book!

**Comment by gmiodice** [comment]
Hi @fabianpedd, thanks for your suggestion. Absolutely! I add it in the `README.md` file.

**Comment by gmiodice** [comment]
Just added the citation section in the `REAME.md` file. Thanks again @fabianpedd !
