### ISSUE TITLE
training issue using tensorflow last version

### ISSUE THREAD

**Issue by kauly** [PacktPublishing/TinyML-Cookbook#6]
I had a problem during the training phase of the first project, the weather station.  It was necessary to make the following change to not have a *libdevice not found* error:

**from this**
```python
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
```
**to this**
```python
model.compile(loss='binary_crossentropy', optimizer=tf.keras.optimizers.legacy.Adam(), metrics=['accuracy'])
```

Using the following libraries in a local conda environment:
```
# Name                    Version                   Build  Channel
tensorflow                2.11.1          cuda112py39h01bd6f0_0    conda-forge
tensorflow-base           2.11.1          cuda112py39h0320e7d_0    conda-forge
tensorflow-estimator      2.11.1          cuda112py39h11d7a3b_0    conda-forge
tensorflow-gpu            2.11.1          cuda112py39h0bbbad9_0    conda-forge
```

**Comment by kauly** [comment]
I found the solution here:
https://discuss.tensorflow.org/t/cant-find-libdevice-directory-cuda-dir-nvvm-libdevice/11896/14

**Comment by gmiodice** [comment]
Hi @kauly ! Many thanks for reporting the issue. Much appreciated. I have added your solution to my list to integrate it in the second edition of the book.

Best,
Gian Marco
